### ISSUE TITLE
Nuking with incorrect args crashes the bot

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot2#146]
This will crash the bot: !nuke a
This will not: !nuke a 1m

```
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: panic: runtime error: slice bounds out of range [1:0]
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: goroutine 138 [running]:
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/modules.(*nukeModule).Trigger(0xc001600790, 0xc000c90a20, 0x2, 0x2, 0x172ecc0, 0xc000be83a0, 0x1737680, 0xc0002695e0, 0x1730940, 0xc0018686c0, ...)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/modules/nuke.go:78 +0x59b
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/commands.(*Commands).OnMessage(0xc000ed5c00, 0x172ecc0, 0xc000be83a0, 0x1737680, 0xc0002695e0, 0x1730940, 0xc0018686c0, 0x1725100, 0xc000f8fb98, 0x17399e0, ...)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/commands/commands.go:41 +0x2ca
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/modules.(*nukeModule).OnMessage(0xc001600790, 0x172ecc0, 0xc000be83a0, 0x1737680, 0xc0002695e0, 0x1730940, 0xc0018686c0, 0x1725100, 0xc000f8fb98, 0x0, ...)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/modules/nuke.go:108 +0x108
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/twitch.(*BotChannel).HandleMessage.func1(0x1735e40, 0xc001600790, 0x0, 0x0)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/twitch/botchannel.go:383 +0x9b
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/twitch.(*BotChannel).OnModules(0xc000f8fb80, 0xc000eb8da0, 0x1, 0x0, 0x0, 0x0)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/twitch/botchannel.go:330 +0xfc
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/twitch.(*BotChannel).HandleMessage(0xc000f8fb80, 0x1737680, 0xc0002695e0, 0x1730940, 0xc0018686c0, 0x434a81, 0xd389a0)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/twitch/botchannel.go:382 +0x16d
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/pajbot/pajbot2/pkg/twitch.(*Bot).HandleMessage(0xc000df0540, 0xc0000c298e, 0x9, 0xc0000c2943, 0x9, 0xc0000c2963, 0x9, 0xc0000c28b3, 0x9, 0xc0000c289e, ...)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/pkg/twitch/bot.go:599 +0x44f
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: main.(*Application).StartBots.func1.1(0xc0000c2943, 0x9, 0xc0000c2963, 0x9, 0xc0000c28b3, 0x9, 0xc0000c289e, 0x7, 0xc000e3b680, 0xc0000c2840, ...)Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/cmd/bot/application.go:540 +0x54a
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/gempir/go-twitch-irc/v2.(*Client).handleLine(0xc001902480, 0xc0000c2840, 0x160, 0x0, 0x1)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot/go/pkg/mod/github.com/gempir/go-twitch-irc/v2@v2.4.2/client.go:933 +0xa1a
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/gempir/go-twitch-irc/v2.(*Client).startParser(0xc001902480, 0xd37680, 0xc001902480)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot/go/pkg/mod/github.com/gempir/go-twitch-irc/v2@v2.4.2/client.go:874 +0x112
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/gempir/go-twitch-irc/v2.(*Client).makeConnection(0xc001902480, 0xc001015e58, 0xc000c29500, 0x0, 0x1e)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot/go/pkg/mod/github.com/gempir/go-twitch-irc/v2@v2.4.2/client.go:727 +0x228
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: github.com/gempir/go-twitch-irc/v2.(*Client).Connect(0xc001902480, 0xcfab06, 0x6)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot/go/pkg/mod/github.com/gempir/go-twitch-irc/v2@v2.4.2/client.go:677 +0x11e
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: main.(*Application).StartBots.func1(0xc0002797c0, 0xc000df0540)
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/cmd/bot/application.go:574 +0x2cd
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]: created by main.(*Application).StartBots
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal start.sh[2535633]:         /opt/pajbot2/cmd/bot/application.go:513 +0xd3
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal systemd[1]: pajbot2.service: Failed to read oom_kill field of memory.events cgroup attribute: No such file or directory
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal systemd[1]: pajbot2.service: Child 2535621 belongs to pajbot2.service.
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal systemd[1]: pajbot2.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Sep 22 12:12:52 Ubuntu-2004-focal-64-minimal systemd[1]: pajbot2.service: Failed with result 'exit-code'.```

**Comment by alazymeme** [comment]
Reproduced on my own bot and leppunen's bot

**Comment by RAnders00** [comment]
fixed via https://github.com/pajbot/pajbot2/commit/13dca9cbbf7c942ca4a75fa5783b434451d0f354
