### ISSUE TITLE
Failing heighreload command

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot2#269]
![image](https://user-images.githubusercontent.com/12804673/103134747-1b168e80-46ff-11eb-8e3f-aaaf8ea35eac.png)

Commit c52650b8

```golang
Dec 25 13:10:03 Ubuntu-2004-focal-64-minimal start.sh[1060354]: 2020/12/25 13:10:03 init channel weest (130924701)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]: System.Text.Json.JsonException: ':' is an invalid end of a number. Expected a delimiter. Path: $ | LineNumber: 0 | BytePositionInLine: 3.
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:  ---> System.Text.Json.JsonReaderException: ':' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 3.
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.Utf8JsonReader.TryGetNumber(ReadOnlySpan`1 data, Int32& consumed)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.Utf8JsonReader.Read()
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    --- End of inner exception stack trace ---
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& readStack, JsonReaderException ex)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.JsonSerializer.ReadCore(Type returnType, JsonSerializerOptions options, Utf8JsonReader& reader)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at MessageHeightTwitch.BTTVEmoteProvider.Initialize(String ChannelId, CancellationToken Token)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at MessageHeightTwitch.MessageHeightTwitch..ctor(String Channel, String ChannelId, Int32 TimeoutMs)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]:    at MessageHeightTwitchStatic.InitChannel(String Channel, String ChannelId, Int32 TimeoutMs)
Dec 25 13:10:04 Ubuntu-2004-focal-64-minimal start.sh[1060354]: 2020/12/25 13:10:04 done
```

**Comment by alazymeme** [comment]
![image](https://user-images.githubusercontent.com/12804673/103148701-558b3480-47ae-11eb-8992-a3d039fa547e.png)

**Comment by alazymeme** [comment]
Fixed by rebuilding the `message_height_limit` module using the `install.sh` script
