### ISSUE TITLE
MessageHeight module not working

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot2#403]
```
System.Text.Json.JsonException: 'e' is an invalid start of a value. Path: $ | LineNumber: 0 | BytePositionInLine: 0.
 ---> System.Text.Json.JsonReaderException: 'e' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, JsonReaderException ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at MessageHeightTwitch.BTTVEmoteProvider.Initialize(String ChannelId, CancellationToken Token)
   at MessageHeightTwitch.MessageHeightTwitch..ctor(String Channel, String ChannelId, Int32 TimeoutMs)
   at MessageHeightTwitchStatic.InitChannel(String Channel, String ChannelId, Int32 TimeoutMs)
Channel alazymeme initialized successfully
Error initializing channel: error reloading height module: Failed to init Channel alazymeme
```

I've tried completely re-cloning the repo, but nothing appears to "make it work":
![image](https://user-images.githubusercontent.com/12804673/115965996-ead8e280-a56e-11eb-906b-74ae80f10623.png)

I'm building with csharp, using the install and build script, but nothing appears to work.

**Comment by RAnders00** [comment]
seems like bttv responsed with something that was not JSON? Do we check response code on the request to BTTV to see whether its 200 OK?

**Comment by pajlada** [comment]
This would be the relevant place to check/add more debugging.
https://github.com/TETYYS/MessageHeightTwitch/blob/master/BTTVEmoteProvider.cs#L53-L117

**Comment by pajlada** [comment]
When https://github.com/TETYYS/MessageHeightTwitch/pull/9 has been merged in, we will update the git submodule and things should work again

**Comment by alazymeme** [comment]
Fixed by https://github.com/pajbot/pajbot2/pull/405
